//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopApp.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public int Login_ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int User_ID { get; set; }
        public int Role_id { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Users Users { get; set; }
    }
}
