//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopApp.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recept_Items
    {
        public int Recept_Item_ID { get; set; }
        public int Recept_ID { get; set; }
        public int Item_ID { get; set; }
    
        public virtual Recepts Recepts { get; set; }
        public virtual Items Items { get; set; }
    }
}
